//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestDemoWinFormEntities : DbContext
    {
        public TestDemoWinFormEntities()
            : base("name=TestDemoWinFormEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bus_SendMsg> Bus_SendMsg { get; set; }
        public virtual DbSet<Log_UserMsg> Log_UserMsg { get; set; }
        public virtual DbSet<Rla_FriendRelation> Rla_FriendRelation { get; set; }
        public virtual DbSet<ViewFriendRelation> ViewFriendRelation { get; set; }
    
        public virtual ObjectResult<Nullable<long>> Proc_GetTransId(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("Proc_GetTransId", userIdParameter);
        }
    }
}
